#!/bin/bash

TEST_DIR=./tests

poetry run pylint --rcfile=.pylintrc src tests sempl.py

mkdir -p ./reports

poetry run pytest ${TEST_DIR}/tg*.py -vvv --md-report --md-report-output=./reports/report.md 
