name: 'Poetry freeze'
description: 'Exports poetry requirements to pip requirements format'
inputs:
  output-file:
    description: 'Name of the output file'
    required: true
  extra-args:
    description: 'Extra poetry arguments'
    required: true
outputs:
  requirements-file:
    description: Pip requirements file
    value: ${{ inputs.output-file }}
runs:
  using: composite
  steps:
    - run: poetry self add poetry-plugin-export
      shell: bash
    
    - run: poetry config warnings.export false
      shell: bash

    - run: poetry export -f requirements.txt ${{ inputs.extra-args }} --output ${{ inputs.output-file }}
      shell: bash
    - run: echo ${{ GITHUB_REF_NAME }}
    # - run: |
    #     git config --global user.email "requirements-bot@github.com"
    #     git config --global user.name "Requirements Bot"
    #     git add ./${{ inputs.output-file }}
    #     git commit -m "chore: freeze requirements"
    #     # git push origin
    #   shell: bash