name: 'Poetry freeze'
description: 'Exports poetry dev and main dependencies to pip requirements'
inputs:
  output-file:
    description: 'Name of the requirements file without extension'
    required: true
  file-extension:
    description: 'Requirements file extension'
    required: false
    default: 'txt'
  dev-postfix:
    description: 'Dev requirements file postfix'
    required: false
    default: 'txt'
runs:
  using: composite
  steps:
    - run: poetry self add poetry-plugin-export
      shell: bash
    
    - run: poetry config warnings.export false
      shell: bash

    - run: |
        poetry export -f requirements.txt --only main \
          --output ${{ inputs.output-file }}.${{ inputs.file-extension }}
      shell: bash
    
    - run: |
        poetry export -f requirements.txt --with dev \
          --output ${{ inputs.output-file }}-${{ inputs.dev-postfix }}.${{ inputs.file-extension }}
      shell: bash

    - run: |
        git config --global user.email "requirements-bot@github.com"
        git config --global user.name "Requirements Bot"
        git add ./${{ inputs.output-file }}.${{ inputs.file-extension }}
        git add ./${{ inputs.output-file }}-${{ inputs.dev-postfix }}.${{ inputs.file-extension }}
        git commit -m "chore: freeze requirements"
        git push origin ${{ github.ref_name }}
      shell: bash