name: CI

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.7.1
        export PATH=~/.local/bin:$PATH
        poetry --version
    
    - name: Install Poetry export plugin
      run: poetry self add poetry-plugin-export

    - name: Install dependencies
      run: poetry install --no-root
    
    - name: Poetry freeze dependencies to requirement.txt
      run: poetry export -f requirements.txt --without-hashes --output requirements.txt

    - name: Run ruff
      run: poetry run ruff check

    - name: Run tests
      run: |
        mkdir -p ./reports
        poetry run pytest tests/tg*.py -vvv --md-report --md-report-output=./reports/report.md

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ./reports
